"""LocalFileProvider — register a file we produced ourselves as a Genblaze step.

The assembled advertisement is not generated by any upstream API: it is cut
locally with ffmpeg from clips that each already have their own manifest. But it
is the artefact the user actually downloads, so it needs the same treatment as
everything else — a Run, a Manifest, a SHA-256, and an upload through the same
ObjectStorageSink.

Wrapping it in a trivial SyncProvider is what buys that. The alternative is
hand-constructing a Manifest and uploading out-of-band, which would mean two
provenance code paths that can disagree — exactly what
app/providers/tokenrouter_chat.py exists to avoid for LLM calls.

The file MUST already live under the system temp dir: ObjectStorageSink's
AssetTransfer enforces ALLOWED_FILE_ROOTS for file:// assets, so anything
written elsewhere fails the upload with StorageError.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

from genblaze_core.exceptions import ProviderError
from genblaze_core.models.asset import Asset
from genblaze_core.models.enums import ProviderErrorCode
from genblaze_core.models.step import Step
from genblaze_core.providers import SyncProvider


class LocalFileProvider(SyncProvider):
    """Attach an existing local file to a step as its output asset.

    Step params:
      path        str  absolute path to the finished file (required)
      media_type  str  MIME type, default video/mp4
    """

    name = "fernwood-local-file"

    def generate(self, step: Step, config: Any = None) -> Step:
        params = step.params or {}
        raw = params.get("path")
        if not raw:
            raise ProviderError(
                "LocalFileProvider requires a 'path' param",
                error_code=ProviderErrorCode.INVALID_REQUEST,
            )

        path = Path(raw)
        if not path.is_file():
            raise ProviderError(
                f"LocalFileProvider: no such file {path}",
                error_code=ProviderErrorCode.INVALID_REQUEST,
            )

        data = path.read_bytes()
        if not data:
            raise ProviderError(
                f"LocalFileProvider: {path} is empty",
                error_code=ProviderErrorCode.INVALID_RESPONSE,
            )

        step.assets.append(
            Asset(
                url=path.resolve().as_uri(),
                media_type=str(params.get("media_type") or "video/mp4"),
                sha256=hashlib.sha256(data).hexdigest(),
                size_bytes=len(data),
            )
        )
        step.metadata["local_path"] = str(path)
        return step
